"""empty message

Revision ID: 0275a532e7c9
Revises: fbcadd49bdcf
Create Date: 2017-07-26 11:27:00.060996

"""

# revision identifiers, used by Alembic.
revision = '0275a532e7c9'
down_revision = 'fbcadd49bdcf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_type')
    # ### end Alembic commands ###
