"""empty message

Revision ID: 02960d059750
Revises: f639a192601d
Create Date: 2017-08-01 10:55:59.727111

"""

# revision identifiers, used by Alembic.
revision = '02960d059750'
down_revision = 'f639a192601d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
