"""empty message

Revision ID: 0f94b20e649f
Revises: 8d948fb68bb5
Create Date: 2017-07-26 10:40:51.917485

"""

# revision identifiers, used by Alembic.
revision = '0f94b20e649f'
down_revision = '8d948fb68bb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'bio')
    # ### end Alembic commands ###
