"""empty message

Revision ID: 1a1b376257f2
Revises: 183213fd72e2
Create Date: 2017-07-31 14:22:09.146556

"""

# revision identifiers, used by Alembic.
revision = '1a1b376257f2'
down_revision = '183213fd72e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
