"""empty message

Revision ID: 1caf72ad93dc
Revises: e0d65c7fb897
Create Date: 2017-07-26 09:38:58.516250

"""

# revision identifiers, used by Alembic.
revision = '1caf72ad93dc'
down_revision = 'e0d65c7fb897'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
