"""empty message

Revision ID: 1e2a51824276
Revises: db50329643c8
Create Date: 2017-08-15 15:07:59.927978

"""

# revision identifiers, used by Alembic.
revision = '1e2a51824276'
down_revision = 'db50329643c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('district', sa.String(length=125), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'district')
    # ### end Alembic commands ###
