"""empty message

Revision ID: 24ba11dcd48b
Revises: ecc5c59e076a
Create Date: 2017-08-01 11:36:00.442720

"""

# revision identifiers, used by Alembic.
revision = '24ba11dcd48b'
down_revision = 'ecc5c59e076a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'created_at')
    # ### end Alembic commands ###
