"""empty message

Revision ID: 302f98b6bd75
Revises: 7aa318cb0dc4
Create Date: 2017-07-25 17:07:33.785197

"""

# revision identifiers, used by Alembic.
revision = '302f98b6bd75'
down_revision = '7aa318cb0dc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('faculty_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('test', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    op.drop_column('users', 'faculty_name')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
