"""empty message

Revision ID: 41ee7f4e6101
Revises: 24ba11dcd48b
Create Date: 2017-08-01 11:37:01.770561

"""

# revision identifiers, used by Alembic.
revision = '41ee7f4e6101'
down_revision = '24ba11dcd48b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefits', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('benefits', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benefits', 'updated_at')
    op.drop_column('benefits', 'created_at')
    # ### end Alembic commands ###
