"""empty message

Revision ID: 7aa318cb0dc4
Revises: 0809b7230820
Create Date: 2017-07-25 17:01:08.212263

"""

# revision identifiers, used by Alembic.
revision = '7aa318cb0dc4'
down_revision = '0809b7230820'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('major_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('university_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'university_name')
    op.drop_column('users', 'major_name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
