"""empty message

Revision ID: 8d948fb68bb5
Revises: a88967ce05f4
Create Date: 2017-07-26 10:40:35.793404

"""

# revision identifiers, used by Alembic.
revision = '8d948fb68bb5'
down_revision = 'a88967ce05f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
