"""empty message

Revision ID: a13a4510b60e
Revises: 0275a532e7c9
Create Date: 2017-07-26 11:40:41.721240

"""

# revision identifiers, used by Alembic.
revision = 'a13a4510b60e'
down_revision = '0275a532e7c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'company_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'type_id')
    # ### end Alembic commands ###
