"""empty message

Revision ID: a6178922590c
Revises: da5ce39df09d
Create Date: 2017-08-01 16:10:11.826885

"""

# revision identifiers, used by Alembic.
revision = 'a6178922590c'
down_revision = 'da5ce39df09d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_skill', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('job_skill', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_skill', 'updated_at')
    op.drop_column('job_skill', 'created_at')
    # ### end Alembic commands ###
