"""empty message

Revision ID: a88967ce05f4
Revises: 79d97fb78b75
Create Date: 2017-07-26 10:39:13.148247

"""

# revision identifiers, used by Alembic.
revision = 'a88967ce05f4'
down_revision = '79d97fb78b75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('overview', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'overview')
    # ### end Alembic commands ###
