"""empty message

Revision ID: afa4bfd7ae94
Revises: 1caf72ad93dc
Create Date: 2017-07-26 09:40:00.490547

"""

# revision identifiers, used by Alembic.
revision = 'afa4bfd7ae94'
down_revision = '1caf72ad93dc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
