"""empty message

Revision ID: c0ed9f294c20
Revises: e730b7703e38
Create Date: 2017-07-25 16:25:31.718038

"""

# revision identifiers, used by Alembic.
revision = 'c0ed9f294c20'
down_revision = 'e730b7703e38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
