"""empty message

Revision ID: d70e672b3656
Revises: 41ee7f4e6101
Create Date: 2017-08-01 11:39:03.873156

"""

# revision identifiers, used by Alembic.
revision = 'd70e672b3656'
down_revision = '41ee7f4e6101'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_type', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('company_type', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_type', 'updated_at')
    op.drop_column('company_type', 'created_at')
    # ### end Alembic commands ###
