"""empty message

Revision ID: e0d65c7fb897
Revises: 302f98b6bd75
Create Date: 2017-07-25 17:07:48.453468

"""

# revision identifiers, used by Alembic.
revision = 'e0d65c7fb897'
down_revision = '302f98b6bd75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
