"""empty message

Revision ID: ecc5c59e076a
Revises: 02960d059750
Create Date: 2017-08-01 11:00:38.041921

"""

# revision identifiers, used by Alembic.
revision = 'ecc5c59e076a'
down_revision = '02960d059750'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('avatar', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'avatar')
    # ### end Alembic commands ###
