"""empty message

Revision ID: fbcadd49bdcf
Revises: 0f94b20e649f
Create Date: 2017-07-26 11:12:30.395157

"""

# revision identifiers, used by Alembic.
revision = 'fbcadd49bdcf'
down_revision = '0f94b20e649f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    # ### end Alembic commands ###
